FIX: Fixes dot() returning NaN.
kvartborg/vector pull request #26
Opened 2022-09-21 20:29 UTC by SolarLune

Here's a PR to fix angle() sometimes returning NaN with specific long-running vectors; this is probably due to floating-point inaccuracies.

As an example, without this PR, this:
```go
v := vector.Vector{-0.9040721420170615, 0, 0.4273798802338293}
fmt.Println(v.Angle(v))
```
returns NaN instead of 0 (and similarly NaN instead of `pi` if the vector were to be tested against its opposite).

2022-09-23 12:20 UTC, kvartborg requested changes
Thank you for fixing this @SolarLune, can i get you to add a unit test to catch this case?

2022-09-24 04:14 UTC, SolarLune commented
Whoops, sorry about that - OK, I force updated my master branch so the current PR now includes a simple dot NaN test.

2022-09-26 16:13 UTC, kvartborg approved these changes
No problem, looks good! 👍

2022-09-26 17:54 UTC, SolarLune commented
Excellent - and sorry for the confusing title / description, haha. This issue affects both dot() and angle().

2022-09-26 18:07 UTC, kvartborg commented
Yeah, i figured that out after seeing the code. Once again thanks for the contribution! :)

2022-09-26 18:07 UTC, merged